# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - L_B_COX_joint
    - L_B_FEM_joint
    - L_B_TIB_joint
    - L_F_COX_joint
    - L_F_FEM_joint
    - L_F_TIB_joint
    - L_M_COX_joint
    - L_M_FEM_joint
    - L_M_TIB_joint
    - R_B_COX_joint
    - R_B_FEM_joint
    - R_B_TIB_joint
    - R_F_COX_joint
    - R_F_FEM_joint
    - R_F_TIB_joint
    - R_M_COX_joint
    - R_M_FEM_joint
    - R_M_TIB_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: leg_R_F_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - R_F_COX_joint
      - R_F_FEM_joint
      - R_F_TIB_joint
  - name: leg_R_M_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - R_M_COX_joint
      - R_M_FEM_joint
      - R_M_TIB_joint
  - name: leg_R_B_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - R_B_COX_joint
      - R_B_FEM_joint
      - R_B_TIB_joint
  - name: leg_L_F_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - L_F_COX_joint
      - L_F_FEM_joint
      - L_F_TIB_joint
  - name: leg_L_M_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - L_M_COX_joint
      - L_M_FEM_joint
      - L_M_TIB_joint
  - name: leg_L_B_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - L_B_COX_joint
      - L_B_FEM_joint
      - L_B_TIB_joint
even_coxa:
  type: position_controllers/JointPositionController
  joints:
    - R_M_COX_joint
    - R_M_FEM_joint
    - R_M_TIB_joint
    - L_F_COX_joint
    - L_F_FEM_joint
    - L_F_TIB_joint
    - L_B_COX_joint
    - L_B_FEM_joint
    - L_B_TIB_joint
  gains:
    R_M_COX_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_M_FEM_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_M_TIB_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_F_COX_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_F_FEM_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_F_TIB_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_B_COX_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_B_FEM_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_B_TIB_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1